spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: true

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: Error






