server:
    port: 8084
spring:
    application:
        name: employee-service
    datasource:
      username: postgres
      password: secret
      url: jdbc:postgresql://localhost:5432/employee
    # Configuration Server
    cloud:
        config:
            uri: http://localhost:8071
            fail-fast: true

    jpa:
        hibernate:
            ddl-auto: create
            defer-datasource-initialization: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                show-sql: true

    profiles:
        active: default

eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka

logging:
    level:
        root: DEBUG
        org:
            hibernate:
                SQL: WARN
        springframework:
            boot:
                autoconfigure: DEBUG

