server:
  port: 8082
spring:
  application:
    name: login-service
  datasource:
    username: root
    password: secret
    url: jdbc:mysql://localhost:3306/loginservice

  # Configuration Server
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: true

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show-sql: true

  profiles:
    active: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      hibernate:
        SQL: WARN
    springframework:
      boot:
        autoconfigure: ERROR

    root: ERROR
